In [1]:
import numpy as np

In [2]:
aravali = np.array(np.random.randint(10, 40, (8,2)))
print(f"The defined array is \n{aravali}")
print(f"The shape of the array is {aravali.shape}")

The defined array is 
[[24 32]
 [37 22]
 [25 17]
 [21 11]
 [32 38]
 [27 20]
 [21 35]
 [19 26]]
The shape of the array is (8, 2)


In [3]:
nilgiri = np.transpose(aravali)
print(f"The transposed array is \n {nilgiri}")
print(f"The shape of transposed array is {nilgiri.shape}")

The transposed array is 
 [[24 37 25 21 32 27 21 19]
 [32 22 17 11 38 20 35 26]]
The shape of transposed array is (2, 8)


In [4]:
new_3d_array = np.array(np.random.randint(5,50,(3,5,2)))
print(new_3d_array)
print(f"The shape of array is {new_3d_array.shape}")

[[[17 16]
  [15 13]
  [25  9]
  [31 26]
  [45  7]]

 [[ 8 40]
  [45 42]
  [28 10]
  [23  7]
  [18 37]]

 [[21 15]
  [18 31]
  [32 42]
  [37 41]
  [16  6]]]
The shape of array is (3, 5, 2)


In [5]:
transposed_array = np.transpose(new_3d_array)
print(transposed_array)
print(f"The shape of the array is {transposed_array.shape}")

[[[17  8 21]
  [15 45 18]
  [25 28 32]
  [31 23 37]
  [45 18 16]]

 [[16 40 15]
  [13 42 31]
  [ 9 10 42]
  [26  7 41]
  [ 7 37  6]]]
The shape of the array is (2, 5, 3)


In [6]:
#New 2d array
array_2d = np.array(np.random.randint(1,10,(2,10)))
print(array_2d)
print(array_2d.shape)

[[9 3 1 5 1 9 5 1 2 4]
 [6 2 5 8 2 6 4 2 5 7]]
(2, 10)


In [7]:
new_shape = (2,5,2)
reshaped_array = np.reshape(array_2d, new_shape)
print(reshaped_array)
print(reshaped_array.shape)

[[[9 3]
  [1 5]
  [1 9]
  [5 1]
  [2 4]]

 [[6 2]
  [5 8]
  [2 6]
  [4 2]
  [5 7]]]
(2, 5, 2)


In [8]:
new_shape = (5,2,2)
reshaped_array = np.reshape(array_2d, new_shape)
print(reshaped_array)
print(reshaped_array.shape)

[[[9 3]
  [1 5]]

 [[1 9]
  [5 1]]

 [[2 4]
  [6 2]]

 [[5 8]
  [2 6]]

 [[4 2]
  [5 7]]]
(5, 2, 2)


In [9]:
random_3d_array = np.array(np.random.randint(1,20,(2,4,2)))
print(random_3d_array)
print(random_3d_array.shape)

[[[15  7]
  [ 5  4]
  [ 6 13]
  [10  1]]

 [[18 10]
  [14  9]
  [ 9  5]
  [ 8 14]]]
(2, 4, 2)


In [10]:
new_shape = (4,1,4)
reshaped_array = np.reshape(random_3d_array, new_shape)
print(reshaped_array)
print(reshaped_array.shape)

[[[15  7  5  4]]

 [[ 6 13 10  1]]

 [[18 10 14  9]]

 [[ 9  5  8 14]]]
(4, 1, 4)


In [11]:
new_shape = (4,1,8)
reshaped_array = np.resize(random_3d_array, new_shape)
print(reshaped_array)
print(reshaped_array.shape)

[[[15  7  5  4  6 13 10  1]]

 [[18 10 14  9  9  5  8 14]]

 [[15  7  5  4  6 13 10  1]]

 [[18 10 14  9  9  5  8 14]]]
(4, 1, 8)


In [12]:
random_3d_array.resize(new_shape)

In [13]:
print(random_3d_array)

[[[15  7  5  4  6 13 10  1]]

 [[18 10 14  9  9  5  8 14]]

 [[ 0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0]]]


In [14]:
random_3d_array = np.array(np.random.randint(1,10,(2,3,4)))
print(random_3d_array)
print(random_3d_array.shape)

[[[7 7 3 9]
  [9 2 7 9]
  [2 8 8 5]]

 [[3 2 4 1]
  [9 8 4 4]
  [2 1 2 8]]]
(2, 3, 4)


In [15]:
random_3d_array.flatten()

array([7, 7, 3, 9, 9, 2, 7, 9, 2, 8, 8, 5, 3, 2, 4, 1, 9, 8, 4, 4, 2, 1,
       2, 8], dtype=int32)

In [16]:
random_3d_array.flatten(order='C')

array([7, 7, 3, 9, 9, 2, 7, 9, 2, 8, 8, 5, 3, 2, 4, 1, 9, 8, 4, 4, 2, 1,
       2, 8], dtype=int32)

In [17]:
random_3d_array.flatten(order='F')

array([7, 3, 9, 9, 2, 2, 7, 2, 2, 8, 8, 1, 3, 4, 7, 4, 8, 2, 9, 1, 9, 4,
       5, 8], dtype=int32)

In [18]:
a = np.array(np.random.randint(10,20,(2,3,4)))
print(a)
print(a.shape)

[[[14 11 13 13]
  [15 12 12 16]
  [19 18 17 11]]

 [[18 10 18 18]
  [16 12 18 15]
  [10 13 10 13]]]
(2, 3, 4)


In [19]:
np.insert(a,1,100,axis=0)

array([[[ 14,  11,  13,  13],
        [ 15,  12,  12,  16],
        [ 19,  18,  17,  11]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[ 18,  10,  18,  18],
        [ 16,  12,  18,  15],
        [ 10,  13,  10,  13]]], dtype=int32)

In [20]:
np.insert(a,0,100,axis=1)

array([[[100, 100, 100, 100],
        [ 14,  11,  13,  13],
        [ 15,  12,  12,  16],
        [ 19,  18,  17,  11]],

       [[100, 100, 100, 100],
        [ 18,  10,  18,  18],
        [ 16,  12,  18,  15],
        [ 10,  13,  10,  13]]], dtype=int32)

In [21]:
np.insert(a,0,100,axis=2)

array([[[100,  14,  11,  13,  13],
        [100,  15,  12,  12,  16],
        [100,  19,  18,  17,  11]],

       [[100,  18,  10,  18,  18],
        [100,  16,  12,  18,  15],
        [100,  10,  13,  10,  13]]], dtype=int32)

In [22]:
a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[5 4 3]
  [5 4 2]
  [2 5 4]]

 [[4 2 3]
  [3 3 5]
  [5 3 5]]]
(2, 3, 3)


In [23]:
np.append(a,55)

array([ 5,  4,  3,  5,  4,  2,  2,  5,  4,  4,  2,  3,  3,  3,  5,  5,  3,
        5, 55])

In [24]:
b = np.random.randint(2,6,(2,1,3))
print(b)

[[[2 5 5]]

 [[2 5 5]]]


In [25]:
np.append(a,b,axis=1)

array([[[5, 4, 3],
        [5, 4, 2],
        [2, 5, 4],
        [2, 5, 5]],

       [[4, 2, 3],
        [3, 3, 5],
        [5, 3, 5],
        [2, 5, 5]]], dtype=int32)

In [26]:
a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[2 5 4]
  [2 3 4]
  [2 4 4]]

 [[5 4 5]
  [3 3 5]
  [4 2 4]]]
(2, 3, 3)


In [27]:
np.delete(a,(0),axis=0)

array([[[5, 4, 5],
        [3, 3, 5],
        [4, 2, 4]]], dtype=int32)

In [28]:
np.delete(a,(0),axis=1)

array([[[2, 3, 4],
        [2, 4, 4]],

       [[3, 3, 5],
        [4, 2, 4]]], dtype=int32)

In [29]:
np.delete(a,(0),axis=2)

array([[[5, 4],
        [3, 4],
        [4, 4]],

       [[4, 5],
        [3, 5],
        [2, 4]]], dtype=int32)

In [30]:
a = np.random.randint(2,20,(2,3,3))
print(a)
print(a.shape)

[[[14  7 13]
  [17  2  7]
  [ 2 18 11]]

 [[18 19  3]
  [ 9 18  2]
  [ 8 12 16]]]
(2, 3, 3)


In [31]:
np.unique(a)

array([ 2,  3,  7,  8,  9, 11, 12, 13, 14, 16, 17, 18, 19], dtype=int32)

In [32]:
a = [1,2,3]
b = a
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[10, 2, 3]


In [33]:
a = [1,2,3]
b = a.copy()
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[1, 2, 3]


In [34]:
np.arange(3) + 5

array([5, 6, 7])

In [35]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [36]:
a=np.random.randint(2,6,(2,4))
print(a)
b=np.random.randint(0,5,(2,4))
print(b)

[[2 5 5 2]
 [3 2 4 3]]
[[4 4 3 2]
 [0 3 3 3]]


In [37]:
np.multiply(a,b)

array([[ 8, 20, 15,  4],
       [ 0,  6, 12,  9]], dtype=int32)

In [38]:
np.divide(a,b)

C:\Users\HP\AppData\Local\Temp\ipykernel_15164\2626738034.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,b)


array([[0.5       , 1.25      , 1.66666667, 1.        ],
       [       inf, 0.66666667, 1.33333333, 1.        ]])

In [39]:
a=np.random.randint(5,9,(2,4))
print(a)

[[7 5 7 7]
 [7 5 8 7]]


In [40]:
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

53
[14 10 15 14]
[26 27]


In [41]:
print(np.min(a))
print(np.min(a,axis=1))

5
[5 5]


In [42]:
print(np.sort(a,axis=0))

[[7 5 7 7]
 [7 5 8 7]]


In [43]:
print(np.sort(a,axis=1))

[[5 7 7 7]
 [5 7 7 8]]
